### PR TITLE
Blog post about how to build a places app with Onsen + Foursquare + Google Maps

### PR DESCRIPTION
**Pull request by philolo1**
This is the draft of my blog post about building an app with onsen-ui. I changed the date to 27, because I was told we wanted to publish something different in the next days. 

The app can be looked at : http://philolo1.github.io/OnsenUI-Places-App/  and https://github.com/philolo1/OnsenUI-Places-App

@argelius

### CODE REVIEW

**Comment by argelius** [comment]
Thank you @philolo1 ! I will try to publish this on Wednesday

**Comment by philolo1** [comment]
@argelius when should we publish this?

**Comment by andipavllo** [comment]
@philolo1 @argelius there are other blog posts in the queue, I'll publish one today. Let's publish this one next week!

**Comment by philolo1** [comment]
@andipavllo +1:

**Pull request merged**
