### PR TITLE
Add blog post about React

### PR DESCRIPTION
**Pull request by argelius**
@frankdiox @unaso @philolo1 

Can you take a look at this blog post? Please fix errors and give feedback. :)

### CODE REVIEW

**Comment by masahirotanaka** [comment]
Just read the whole article. Wonderful amount of content in here!
I was surprised you (or @philolo1) already done Tabbar as well...

**Comment by argelius** [comment]
Thanks @masahirotanaka ! 

@philolo1 has done some amazing work :dancer: 
I will publish this tomorrow.

**Comment by frankdiox** [comment]
@argelius Awesome, it looks even simple... :)
The only typo I've found is: `We're hope you are as excited as us` :+1:

**Comment by argelius** [comment]
Thanks @frankdiox ! Fixed it.

**Pull request merged**
