### PR TITLE
Popvox blog post (Dec)

### PR DESCRIPTION
**Pull request by unaso**
@argelius @masahirotanaka @andipavllo please check the blog draft

### CODE REVIEW

**Comment by argelius** [comment]
@una: This looks really good. I tried to find a mistake but wasn't able to :)

**Comment by masahirotanaka** [comment]
I enjoyed reading your article. Thanks for the great post!

**Comment by una** [comment]
wrong @una :P

**Comment by argelius** [comment]
@una Sorry about that :)

**Comment by andipavllo** [comment]
Great job @unaso! I just noticed some missing articles, you can find them in my comments :)

**Pull request merged**
