### PR TITLE
Two articles for onsen.ui blog

### PR DESCRIPTION
**Pull request by moongift**
I wrote two articles that abstruct is below.

- Using Riot.js with Monaca
- About security with Monaca

### CODE REVIEW

**Comment by moongift** [comment]
I don't know about how to write a image path. If my method is wrong, teach me please.

**Comment by argelius** [comment]
@moongift The images are correct but I changed from relative to absolute URL.

Both your articles had the same `id` property, please specify different IDs for your posts since it will become the URL:

If the id is `angularjs-15` the URL will become:
https://ja.onsen.io/blog/angularjs-15/

投稿をありがとうございます！マージしました

**Comment by moongift** [comment]
@andipavllo 
Oh, sorry about duplicate id and thank you merging.

**Comment by argelius** [comment]
@moongift 

ブログ記事を投稿しました
https://ja.onsen.io/blog/monaca-riotjs/
https://ja.onsen.io/blog/monaca-app-security-tips/

**Comment by argelius** [comment]
@moongift Also, when you write several articles can you split them into more than one PR? In that case I can post them in different days.

**Pull request merged**
