### PR TITLE
Blog babel

### PR DESCRIPTION
**Pull request by jackchuka**
@andipavllo @argelius @unaso 
Hi, 
I've translated blog post 1434.
please check

Thank you.
Masanori

### CODE REVIEW

**Comment by argelius** [comment]
Thanks @jackchuka ! :+1: 
Hope you can make it to the meetup next week!

@andipavllo Can you add a header image to this blog post when you merge it?

**Comment by andipavllo** [comment]
@jackchuka thanks!

@argelius Yes sure, but I will probably publish some older translations first.

**Comment by argelius** [comment]
@andipavllo No problem. Also for other translations, I think they look a lot better if they have a image in the header.

**Comment by andipavllo** [comment]
@argelius I just noticed this message. Nevertheless, I have already added the image to the header in the new blog posts. There are just a couple of old ones without it, which I'll add soon.

I'm going to publish this one now.

**Comment by argelius** [comment]
Thanks! :+1:

**Pull request merged**
