### PR TITLE
Add English blog post about Onsen UI 2.2.x and improvement on iOS.

### PR DESCRIPTION
**Pull request by asial-matagawa**
@misterjunio 
I wrote a draft of an English blog post but I think English in this post must be improved.
Could you correct my draft and its contents?

@frandiox 
Do you think the contents of this post have a problem?

### CODE REVIEW

**Comment by asial-matagawa** [comment]
If you help me correct this draft, I would be appreciate if you directly push commits to `blog-onsenui-recent-updates` branch.

**Comment by frandiox** [comment]
@asial-matagawa @misterjunio Thanks a lot for the article and rewording. I think it's good to explain about these updates. Just a couple of things:

* Perhaps it's not necessary to explain how to upgrade to the latest version since the process has not changed at all. It's the same as always, right? I find it weird to explain it in an article like this.
* Things like `technically difficult to safely run Onsen UI on iOS` might be a bit negative. It is true that it was hard for us, Onsen UI developers, to support iOS sometimes. But from the user's perspective, it was working well and will still works, right?

**Comment by asial-matagawa** [comment]
@frandiox
Thank you for the feedback!

>Perhaps it's not necessary to explain how to upgrade to the latest version since the process has not changed at all. It's the same as always, right? I find it weird to explain it in an article like this.

Actually it was for Japanese users, so we can remove them for English users.
I will remove them.

>Things like technically difficult to safely run Onsen UI on iOS might be a bit negative. It is true that it was hard for us, Onsen UI developers, to support iOS sometimes. But from the user's perspective, it was working well and will still works, right?

As you pointed out, my words are a bit pessimistic.
I think we should be more confident too. In fact we implemented many things to support iOS while the polyfills were not fully prepared.

@misterjunio
Thank you for correcting my post!
The new sentences look very natural.
Sorry for interrupting you but could you fix my post according to @frandiox's suggestion?

**Comment by misterjunio** [comment]
@asial-matagawa sure, will do 👍

**Comment by asial-matagawa** [comment]
@misterjunio 
Thank you for fixing!
I will publish this post after contacting @yukisekiguchi or someone.

**Pull request merged**
