### PR TITLE
Blog post: `Status of Vue 2 binding alpha and roadmap for beta`

### PR DESCRIPTION
**Pull request by asial-matagawa**
@yukisekiguchi @masahirotanaka @frandiox @misterjunio 

This is a new blog post describing the status of our Vue 2 binding and already proofread by @misterjunio (#355).

### CODE REVIEW

**Comment by frandiox** [comment]
@asial-matagawa Good job! Few things here:
I think the examples with the already deprecated things (like methods API or VOnsIndex) might not be very interesting for users. Better to just write how to do it with the current development version, in my opinion.
About the slots, I'm trying to avoid them as much as possible in favor of props. For example:
`<v-ons-navigator :page-stack="[p1, p2]"></v-ons-navigator>`.
I'll try to keep the support for slots, though.

If you want some examples with the latest API:

```
<v-ons-carousel :index="i" @swipe="i = $event" ... >
```

```
<v-ons-splitter-side :open="isOpen" @swipe="isOpen = $event">
```

**Comment by asial-matagawa** [comment]
@frandiox 
Thank you, I will make some changes according to your suggestion.

>About the slots, I'm trying to avoid them as much as possible in favor of props.

Oh, I see.
I understand as follows:
```
Priority:
  properties  =  events  >  slots  >  (methods)
```

**Comment by frandiox** [comment]
@asial-matagawa Exactly, that's the priority :)

Another thing I forgot, I think we should have e2e tests for the beta release.

**Comment by asial-matagawa** [comment]
@frandiox 
>Another thing I forgot, I think we should have e2e tests for the beta release.

Thank you, I will add it to the list.

**Comment by frandiox** [comment]
@asial-matagawa I think the [latest commit](https://github.com/OnsenUI/OnsenUI/pull/1837/commits/5f12d96032686c208b59306469848111366e6e77) could be nice to show something about Navigator.

Basically, it now requires `pageStack` prop, and can be used optionally with slots if the user wants more control (like passing down props). This can play well with Vuex (having the `pageStack` in a store). Also, the back button automatically pops 1 page from the `pageStack` provided to the VOnsNavigator. If the user wants to reset to the first page on back button click instead of popping only 1 page, it's as easy as running `event.preventDefault()` or using Vue modifier for events:  `<v-ons-back-button @click.prevent="pageStack.splice(1, pageStack.length - 1)">` :smiley:

**Comment by asial-matagawa** [comment]
@frandiox 
>I think the examples with the already deprecated things (like methods API or VOnsIndex) might not be very interesting for users. Better to just write how to do it with the current development version, in my opinion.

Actually I added the deprecated things as anti-patterns like [this style guide](https://angular.io/styleguide#!#03-01), so I would like to keep it with the caution (which I forgot to add):

```html
<!-- Using methods (obsoleted, do not use) -->
<v-ons-navigator ref="myNavigator" :page="page1"></v-ons-navigator>
...

this.$refs.myNavigator.pushPage(page2);
```

```html
<!-- Using custom directives (obsoleted, do not use) -->
<v-ons-carousel v-ons-index="carouselIndex">
  ...
</v-ons-carousel>
```

**Comment by frandiox** [comment]
@asial-matagawa The things is that those methods are not exposed anymore in the Vue components, so it will crash in `alpha.1`. Only works in `alpha.0`. I don't really mind if you keep that info, but it will only be useful for people using `alpha.0` in the future :/

**Comment by asial-matagawa** [comment]
@frandiox 
>This can play well with Vuex (having the pageStack in a store). Also, the back button automatically pops 1 page from the pageStack provided to the VOnsNavigator. If the user wants to reset to the first page on back button click instead of popping only 1 page, it's as easy as running event.preventDefault() or using Vue modifier for events: <v-ons-back-button @click.prevent="pageStack.splice(1, pageStack.length - 1)"> 😃

Nice design! Let's write the advantage of properties into the docs in some time.

----

>@asial-matagawa The things is that those methods are not exposed anymore in the Vue components, so it will crash in alpha.1. Only works in alpha.0. I don't really mind if you keep that info, but it will only be useful for people using alpha.0 in the future :/

OK, I will remove the deprecated examples.
No deprecated examples makes hard to understand what was obsoleted, but come to think of it, users are not interested in such things from the beginning...

**Comment by asial-matagawa** [comment]
@yukisekiguchi @masahirotanaka

The 2nd fix is done. Could you check this?

**Comment by asial-matagawa** [comment]
I will merge this.

**Pull request merged**
