### PR TITLE
Add blog post

### PR DESCRIPTION
**Pull request by argelius**
@masahirotanaka @frankdiox @unaso 

Please take a look at this post when you have time.

### CODE REVIEW

**Comment by masahirotanaka** [comment]
@argelius Thanks for the blog post! I enjoyed reading it.

Here are some suggestions from my end. Please ignore if you feel it doesn't right.

* I suggest title as: "Preview! New Vue.js support for Onsen UI."
* I think it's better to write a separate blog post for the introduction piece, which is now being written in "Templates", "Components" and ".vue files" section. However, I suggest to put "Onsen UI Hello World" example, rather than a plain Vue.js example without Onsen UI.
  * So, I prefer "Install Bindings" right after the first section of "What is Vue.js".
  * And add "Hello World with Onsen UI" before "Navigator example". A simple example before a complex one.
* Change "Conclusion" to "Help us spread the word!"

**Comment by argelius** [comment]
Tänka!

**Comment by masahirotanaka** [comment]
Tänka sounds like "Thanks" but it really means "[Think](https://translate.google.com/#auto/ja/T%C3%A4nka)!"

**Comment by argelius** [comment]
@masahirotanaka I tried to write "thanks" but my phone automatically changed it since it was set to Swedish. :)

**Comment by argelius** [comment]
@masahirotanaka I have updated the blog post now and I created another template that is simpler than the Navigator example.

I will publish this if there are no problems.

**Comment by masahirotanaka** [comment]
Looks good!

**Pull request merged**
