### PR TITLE
Tentative blog post for February 22.

### PR DESCRIPTION
**Pull request by misterjunio**
@masahirotanaka @frankdiox @asial-matagawa I just submitted a tentative version for the next blog post about Angular2 which I would appreciate if you could take a look at. Tbh it concerns more Monaca than OnsenUI but since the goal is to target Angular2 binding users I think it's fine to leave it connected to `onsen` product.

### CODE REVIEW

**Comment by asial-matagawa** [comment]
@misterjunio 
I have checked your draft. Great work!
What I could say is:
- I think you used some images which are not allowed to use/modify.
  Please consider using the following official resources:
    - Angular: https://angular.io/presskit.html
    - Cordova: https://cordova.apache.org/artwork/
- `Angular2` should be `Angular 2`.
    - Actually the official name is `Angular` (See: https://medium.com/google-developer-experts/angular-new-naming-guidelines-eacbebd09363), but `Angular 2` is common now
- `LocalKit` should be `Localkit`.

**Comment by asial-matagawa** [comment]
@misterjunio 
Also, it seems that you replaced the submodule `dist/v2/OnsenUI` with a symbolic link, but this change might break CircleCI on [OnsenUI/onsen.io](https://github.com/OnsenUI/onsen.io).
Could you revert the change about `dist/v2/OnsenUI`?

**Comment by misterjunio** [comment]
@asial-matagawa Oh that's right, I did that to write some documentation before it was merged to master branch. I will apply all your suggested changes now.

**Comment by misterjunio** [comment]
@asial-matagawa I pushed the changes you suggested 👍  Hope everything is ok now.

**Comment by asial-matagawa** [comment]
@misterjunio 
Thank you for accepting my suggestion. I think it is fine now

@masahirotanaka @frankdiox 
Is there any suggestion?

**Comment by frankdiox** [comment]
Looks good! :+1:

**Pull request merged**
